name: vlm_pathology
channels:
  - pytorch
  - conda-forge
dependencies:
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - certifi=2025.8.3
  - cffi=2.0.0
  - charset-normalizer=3.4.3
  - cpython=3.11.13
  - filelock=3.19.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - jinja2=3.1.6
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=21.1.2
  - libdeflate=1.24
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsqlite=3.50.4
  - libtiff=4.7.1
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markupsafe=3.0.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.5
  - openjpeg=2.5.4
  - openssl=3.5.3
  - pillow=11.3.0
  - pip=25.2
  - pthread-stubs=0.4
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.11.13
  - python_abi=3.11
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.5
  - setuptools=80.9.0
  - sympy=1.14.0
  - tk=8.6.13
  - torchaudio=2.5.1
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - bleach==6.2.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.60.0
      - fsspec==2025.9.0
      - ftfy==6.3.1
      - h5py==3.14.0
      - hf-xet==1.1.10
      - huggingface-hub==0.17.3
      - inquirerpy==0.3.4
      - kaggle==1.7.4.5
      - kiwisolver==1.4.9
      - matplotlib==3.10.6
      - numpy==1.25.0
      - packaging==25.0
      - pfzy==0.3.4
      - prompt-toolkit==3.0.52
      - protobuf==6.32.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-slugify==8.0.4
      - regex==2025.9.18
      - safetensors==0.6.2
      - six==1.17.0
      - text-unidecode==1.3
      - tokenizers==0.14.1
      - torch==2.1.0
      - torchvision==0.16.0
      - tqdm==4.67.1
      - transformers==4.35.0
      - wcwidth==0.2.14
      - webencodings==0.5.1
